// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// LocalTime provides a mock function with given fields: timeZoneName
func (_m *Service) LocalTime(timeZoneName string) time.Time {
	ret := _m.Called(timeZoneName)

	if len(ret) == 0 {
		panic("no return value specified for LocalTime")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(timeZoneName)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Service_LocalTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalTime'
type Service_LocalTime_Call struct {
	*mock.Call
}

// LocalTime is a helper method to define mock.On call
//   - timeZoneName string
func (_e *Service_Expecter) LocalTime(timeZoneName interface{}) *Service_LocalTime_Call {
	return &Service_LocalTime_Call{Call: _e.mock.On("LocalTime", timeZoneName)}
}

func (_c *Service_LocalTime_Call) Run(run func(timeZoneName string)) *Service_LocalTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Service_LocalTime_Call) Return(_a0 time.Time) *Service_LocalTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_LocalTime_Call) RunAndReturn(run func(string) time.Time) *Service_LocalTime_Call {
	_c.Call.Return(run)
	return _c
}

// Now provides a mock function with given fields:
func (_m *Service) Now() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// Service_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type Service_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *Service_Expecter) Now() *Service_Now_Call {
	return &Service_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *Service_Now_Call) Run(run func()) *Service_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Now_Call) Return(_a0 time.Time) *Service_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Now_Call) RunAndReturn(run func() time.Time) *Service_Now_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
