version: '3.9'

x-networking: &x-networking
  - service_mesh

x-environment-variables: &x-environment-variables
  - MONGODB_URI=
  - MONGODB_NAME=richpanel
  - KAFKA_BROKERS=sparkly-services-kafka-broker:9092

services:
  sparkly-services-zookeeper:
    image: wurstmeister/zookeeper
    container_name: sparkly-services-zookeeper
    ports:
      - "2181:2181"
    networks: *x-networking

  sparkly-services-kafka-broker:
    image: wurstmeister/kafka
    container_name: sparkly-services-kafka-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://sparkly-services-kafka-broker:9092
      KAFKA_ZOOKEEPER_CONNECT: sparkly-services-zookeeper:2181
      KAFKA_CREATE_TOPICS: "principal.sparkly-services.logins.log:1:1,principal.sparkly-services.posts.log:1:1"
    networks: *x-networking
    depends_on:
      - sparkly-services-zookeeper

  sparkly-services-rest:
    image: sparkly-services
    container_name: sparkly-services-rest
    environment: *x-environment-variables
    ports:
      - 8080:8080
    entrypoint: ./main rest
    networks: *x-networking
    depends_on:
      - sparkly-services-kafka-broker
  
  sparkly-services-worker:
    image: sparkly-services
    container_name: sparkly-services-worker
    environment: *x-environment-variables
    entrypoint: ./main kafka
    networks: *x-networking
    depends_on:
      - sparkly-services-kafka-broker

networks:
  service_mesh:
    external: true
